#file: noinspection YAMLSchemaValidation
name: deploy-to-vps
run-name: Deploy to VPS by @${{ github.actor }}

on:
  push:
    branches:
      - main

jobs:
  cleanup:
    runs-on: self-hosted
    steps:
      - name: Stop Server
        if: always()
        run: systemctl stop zz_bot || true
      - name: Clean Up
        if: always()
        run: cd ${{ github.workspace }}; rm -rf PROJECT_FOLDER;

  get:
    runs-on: self-hosted
    needs: cleanup
    steps:
      - name: Checkout repository
        run: git clone https://github.com/Beardrop2/PROJECT_FOLDER.git
      - run: cd PROJECT_FOLDER; pwd; ls -la;

  build:
    runs-on: self-hosted
    needs: get
    defaults:
      run:
          working-directory: ./PROJECT_FOLDER
    steps:
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: git checkout origin/main
      - name: install
        run: pdm install
      - name: build
        run: pdm build

  test:
    runs-on: self-hosted
    needs: build
    defaults:
      run:
          working-directory: ./PROJECT_FOLDER
    steps:
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: lint
        run: pdm run pre-commit
      - name: Run tests
        run: pdm run test || true

  run:
    runs-on: self-hosted
    needs: test
    defaults:
      run:
          working-directory: ./PROJECT_FOLDER
    env:
      UNS_DISCORD_BOT_TOKEN: ${{ secrets.UNS_DISCORD_BOT_TOKEN }}
    steps:
      - run: echo "UNS_DISCORD_BOT_TOKEN=$UNS_DISCORD_BOT_TOKEN" >> .env
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Start Bot
        run: systemctl start zz_bot
      - name: Stat Bot
        run: systemctl status zz_bot
